name: Hourly Contribution

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Random decision
        id: random
        run: |
          CHANCE=$((RANDOM % 100))
          if [ $CHANCE -lt 50 ]; then
            echo "RUN_COMMIT=true" >> $GITHUB_OUTPUT
          else
            echo "RUN_COMMIT=false" >> $GITHUB_OUTPUT
          fi
      - name: Make commit
        if: steps.random.outputs.RUN_COMMIT == 'true'
        run: |
          echo "$(date -u '+%Y-%m-%d %H:%M:%S')" >> contribuition.txt
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add contribuition.txt
          git commit -m "Add hourly contribution"
          git push
